apiVersion: apps/v1
kind: Deployment
metadata:
name: my-deploymentname: pos-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pos-backend
  template:
    metadata:
      labels:
        app: pos-backend
    spec:
      containers:
      - name: pos-backend
        image: pos-backend:latest