apiVersion: v1
kind: Service
metadata:
  name: pos-backend-service
  namespace: default
spec:
  selector:
    app: pos-backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30088
  type: NodePort
